### ISSUE TITLE
Make project name less pejorative

### ISSUE THREAD

**Issue by nickhudkins** [jasonrhodes/togtox#7]
`project.title.replace('dumb', 'silly')`

**Comment by jasonrhodes** [comment]
Just kidding about "wontfix" -- I'm open to this. :)

**Comment by nickhudkins** [comment]
Really I just want to make sure people don't have negative feelings about it. I understand where you are coming from. I just would hate to find out that folks are like "Aw mannn, this isn't dumb, this is me learning, or having fun!"

**Comment by naterkane** [comment]
If anyone is intimidated by this issue because they don't know what pejorative means. 
[https://en.m.wikipedia.org/wiki/Pejorative](https://en.m.wikipedia.org/wiki/Pejorative)

**Comment by nickhudkins** [comment]
2021 has less issues
